### ISSUE TITLE
The test_outputs folder is missing when making predictions

### ISSUE THREAD

**Issue by guokr233** [allenai/SciREX#16]
Hello, thank you for your work.
I have already trained the main scirex model and the secondary coreference model, and obtained two model files, but when I used the command

> scirex_archive=outputs/pwc_outputs/experiment_scirex_full/main \
scirex_coreference_archive=outputs/pwc_outputs/experiment_coreference/main \
cuda_device=<cuda-device-num> \
bash scirex/commands/predict_scirex_model.sh

made predictions, I got this error:

> Evaluating on all Predicted steps 
Traceback (most recent call last):
  File "scirex/evaluation_scripts/scirex_relation_evaluate.py", line 130, in <module>
    main(args)
  File "scirex/evaluation_scripts/scirex_relation_evaluate.py", line 77, in main
    predicted_ner = convert_to_dict(load_jsonl(args.ner_file))
  File "/data/zj/SciREX/scirex_utilities/json_utilities.py", line 18, in load_jsonl
    return [json.loads(line) for line in open(file )]
FileNotFoundError: [Errno 2] No such file or directory: 'test_outputs//ner_predictions.jsonl'
Evaluating on all predicted steps with filtering using gold salient clusters
Traceback (most recent call last):
  File "scirex/evaluation_scripts/scirex_relation_evaluate.py", line 130, in <module>
    main(args)
  File "scirex/evaluation_scripts/scirex_relation_evaluate.py", line 77, in main
    predicted_ner = convert_to_dict(load_jsonl(args.ner_file))
  File "/data/zj/SciREX/scirex_utilities/json_utilities.py", line 18, in load_jsonl
    return [json.loads(line) for line in open(file )]
FileNotFoundError: [Errno 2] No such file or directory: 'test_outputs//ner_predictions.jsonl'

I checked the SciREX folder, there is no test_outputs folder, can you tell me what went wrong?

**Comment by guokr233** [comment]
I have solved it, just create a test_outputs folder in the root directory
